package com.waillio.mhp3rdcompanion

import androidx.test.core.app.ApplicationProvider
import com.waillio.mhp3rdcompanion.data.CompanionRepository
import com.waillio.mhp3rdcompanion.data.GeneratedDataset
import com.waillio.mhp3rdcompanion.data.InvasionProbabilityBand
import com.waillio.mhp3rdcompanion.data.MaterialSourceType
import com.waillio.mhp3rdcompanion.data.invasionRewardPresentationProjection
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import java.security.MessageDigest

@RunWith(RobolectricTestRunner::class)
class InvasionRewardProductionIntegrationTest {
    private val context = ApplicationProvider.getApplicationContext<android.content.Context>()
    private val data by lazy { CompanionRepository(context).data }
    private val generated by lazy {
        context.assets.open("mhp3rd-data.json").bufferedReader().use {
            Json { ignoreUnknownKeys = true }.decodeFromString<GeneratedDataset>(it.readText())
        }
    }

    @Test
    fun schema22ContainsTheFrozen63RowCorpus() {
        assertEquals(31, generated.schemaVersion)
        assertEquals(63, generated.invasionRewardDrops.size)
        assertEquals(63, generated.invasionRewardDrops.map { it.id }.toSet().size)
        assertEquals(mapOf("GUILD_1_2" to 3, "LOW" to 6, "HIGH" to 54), generated.invasionRewardDrops.groupingBy { it.context }.eachCount())
        assertEquals(8, generated.invasionRewardDrops.map { it.monsterId }.toSet().size)
        assertEquals(48, generated.invasionRewardDrops.map { it.gameItemId }.toSet().size)
        assertTrue(generated.invasionRewardDrops.all { it.quantity > 0 && it.probabilityValuePercent == null })
    }

    @Test
    fun repositoryProjectsSeparateItemAndMonsterSources() {
        val drops = generated.invasionRewardDrops
        assertEquals(63, data.materials.flatMap { it.sources }.count { it.type == MaterialSourceType.INVASION_REWARD })
        assertEquals(48, data.materials.count { material -> material.sources.any { it.type == MaterialSourceType.INVASION_REWARD } })
        assertEquals(8, data.monsters.count { it.invasionRewards.isNotEmpty() })
        assertEquals(32, data.monsters.count { it.invasionRewards.isEmpty() })
        assertTrue(data.materials.flatMap { it.sources }.filter { it.type == MaterialSourceType.INVASION_REWARD }
            .all { it.chance == null && it.probabilityBand != null })
        assertTrue(data.monsters.single { it.id == "monster_deviljho" }.invasionRewards.all { it.context == "HIGH" })
        assertEquals(3, data.monsters.single { it.id == "monster_zinogre" }.invasionRewards.map { it.context }.toSet().size)
        assertTrue(drops.none { it.id in generated.rewards.map { reward -> reward.id } })
    }

    @Test
    fun embeddedAssetMatchesIntegratedProductionBytes() {
        val bytes = context.assets.open("mhp3rd-data.json").use { it.readBytes() }
        val sha = MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02X".format(it) }
        assertEquals("657CFA9376FC8CBE56C67E67D4D1A27C455D21021F51E21B62427C8DDBB26155", sha)
        assertFalse(bytes.isEmpty())
    }

    @Test
    fun itemSourcesProjectionUsesMonsterFirstHierarchyAndPreservesEveryRelation() {
        val invasionSources = data.materials.flatMap { it.sources }
            .filter { it.type == MaterialSourceType.INVASION_REWARD }
        val projection = invasionSources.invasionRewardPresentationProjection()

        assertEquals(63, projection.rawRelationCount)
        assertEquals(8, projection.monsterCount)
        assertEquals(invasionSources.map { it.id }.toSet(), projection.rawRelationIds.toSet())
        assertEquals(63, projection.rawRelationIds.size)
        assertEquals(3, invasionSources.count { it.context == "GUILD_1_2" })
        assertEquals(6, invasionSources.count { it.context == "LOW" })
        assertEquals(54, invasionSources.count { it.context == "HIGH" })
        assertTrue(projection.monsters.flatMap { it.contexts }.all { context ->
            context.label !in setOf("GUILD_1_2", "LOW", "HIGH")
        })
        assertTrue(projection.monsters.flatMap { it.entries }.all { entry ->
            entry.displayBand !in setOf("AT_LEAST_20", "TEN_TO_UNDER_20", "FIVE_TO_UNDER_10", "TWO_TO_UNDER_5", "UNDER_2")
        })
    }

    @Test
    fun representativeInvasionFamiliesKeepContextOrderAndDuplicateEntries() {
        fun itemProjection(gameItemId: Int) = data.materials
            .single { it.gameItemId == gameItemId }
            .sources
            .invasionRewardPresentationProjection()

        val fulgurbug = itemProjection(212)
        assertEquals(1, fulgurbug.monsterCount)
        assertEquals(listOf("GUILD_1_2", "LOW", "HIGH"), fulgurbug.monsters.single().contexts.map { it.context })
        assertEquals(listOf(4, 6, 6), fulgurbug.monsters.single().entries.map { it.quantity })

        val infernoSac = itemProjection(261)
        assertEquals(2, infernoSac.monsterCount)
        assertEquals(2, infernoSac.rawRelationCount)

        listOf(560, 561).forEach { gameItemId ->
            val duplicateContext = itemProjection(gameItemId).monsters.single().contexts.single()
            assertEquals("HIGH", duplicateContext.context)
            assertEquals(2, duplicateContext.entries.size)
            assertEquals(listOf(1, 2), duplicateContext.entries.map { it.quantity })
            assertEquals(
                listOf(InvasionProbabilityBand.TEN_TO_UNDER_20, InvasionProbabilityBand.FIVE_TO_UNDER_10),
                duplicateContext.entries.map { it.probabilityBand }
            )
        }
    }
}
