package com.waillio.mhp3rdcompanion

import androidx.test.core.app.ApplicationProvider
import com.waillio.mhp3rdcompanion.data.CompanionRepository
import com.waillio.mhp3rdcompanion.data.MaterialSourceType
import com.waillio.mhp3rdcompanion.data.GeneratedDataset
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import java.security.MessageDigest

@RunWith(RobolectricTestRunner::class)
class SpecialFreeCompletionGrantIntegrationTest {
    private val context = ApplicationProvider.getApplicationContext<android.content.Context>()
    private val generated by lazy {
        context.assets.open("mhp3rd-data.json").bufferedReader().use {
            Json { ignoreUnknownKeys = true }.decodeFromString<GeneratedDataset>(it.readText())
        }
    }

    @Test
    fun heavyArmorSphereHasHonestProgressionGrant() {
        assertEquals(31, generated.schemaVersion)
        assertEquals(61, generated.itemSpecialFreeAcquisitionRelations.size)
        val relation = generated.itemSpecialFreeAcquisitionRelations.single {
            it.relationId == "GUILD_3_TO_8_ALL_HEAVY_ARMOR_SPHERE"
        }
        assertEquals("PROGRESSION_COMPLETION_GRANT", relation.mechanism)
        assertNull(relation.giverId)
        assertEquals(807, relation.outputGameItemId)
        assertEquals(10, relation.outputQuantity)
        assertEquals("PUBLISHED", relation.quantitySemantics)
        assertEquals("ALL_GUILD_3_TO_8_QUESTS_COMPLETE", relation.conditionType)
        assertEquals("GUILD_3_TO_8_ALL_QUESTS_COMPLETE", relation.completionSetId)
        assertFalse(relation.recurring ?: true)
        assertNull(relation.probabilityPercent)
        assertEquals("NOT_APPLICABLE", relation.probabilitySemantics)
    }

    @Test
    fun reverseProjectionUsesProgressionRewardWithoutGiver() {
        val material = CompanionRepository(context).data.materials.single { it.gameItemId == 807 }
        val source = material.sources.single {
            it.type == MaterialSourceType.SPECIAL_FREE && it.id == "GUILD_3_TO_8_ALL_HEAVY_ARMOR_SPHERE"
        }
        assertEquals("PROGRESSION_COMPLETION_GRANT", source.specialFreeMechanism)
        assertNull(source.specialFreeGiverId)
        assertEquals(10, source.quantity)
        assertEquals("ALL_GUILD_3_TO_8_QUESTS_COMPLETE", source.condition)
        assertEquals("GUILD_3_TO_8_ALL_QUESTS_COMPLETE", source.specialFreeCompletionSetId)
    }

    @Test
    fun embeddedJsonHasIntegratedSha() {
        val bytes = context.assets.open("mhp3rd-data.json").use { it.readBytes() }
        val sha = MessageDigest.getInstance("SHA-256").digest(bytes).joinToString("") { "%02X".format(it) }
        assertEquals("657CFA9376FC8CBE56C67E67D4D1A27C455D21021F51E21B62427C8DDBB26155", sha)
        assertTrue(String(bytes, Charsets.UTF_8).contains("GUILD_3_TO_8_ALL_HEAVY_ARMOR_SPHERE"))
    }
}
